
-- Foreign keys --
ALTER TABLE "account_accesses" ADD CONSTRAINT "account_accesses_ibfk_1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "account_accesses" ("user_id");
ALTER TABLE "account_accesses" ADD CONSTRAINT "account_accesses_ibfk_2" FOREIGN KEY ("account_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "account_accesses" ("account_id");
ALTER TABLE "alt_price_products" ADD CONSTRAINT "alt_price_products_ibfk_1" FOREIGN KEY ("alt_price_id") REFERENCES "alt_prices" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "alt_price_products" ("alt_price_id");
ALTER TABLE "alt_price_products" ADD CONSTRAINT "alt_price_products_ibfk_2" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "alt_price_products" ("product_id");
ALTER TABLE "assemble_part_degrade_vouchers" ADD CONSTRAINT "assemble_product_part_ibfk_2" FOREIGN KEY ("assemble_product_part_id") REFERENCES "assemble_product_parts" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "assemble_part_degrade_vouchers" ("assemble_product_part_id");
ALTER TABLE "assemble_part_degrade_vouchers" ADD CONSTRAINT "product_ibfk_1" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "assemble_part_degrade_vouchers" ("product_id");
ALTER TABLE "assemble_part_degrade_vouchers" ADD CONSTRAINT "voucher_ibfk_3" FOREIGN KEY ("voucher_id") REFERENCES "vouchers" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "assemble_part_degrade_vouchers" ("voucher_id");
ALTER TABLE "assemble_part_inventory_products" ADD CONSTRAINT "assemble_product_part_ibfk_1" FOREIGN KEY ("assemble_product_part_id") REFERENCES "assemble_product_parts" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "assemble_part_inventory_products" ("assemble_product_part_id");
ALTER TABLE "assemble_product_histories" ADD CONSTRAINT "assemble_product_histories_ibfk_1" FOREIGN KEY ("assemble_product_id") REFERENCES "assemble_products" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "assemble_product_histories" ("assemble_product_id");
ALTER TABLE "assemble_product_parts" ADD CONSTRAINT "assemble_product_ibfk_1" FOREIGN KEY ("assemble_product_id") REFERENCES "assemble_products" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "assemble_product_parts" ("assemble_product_id");
ALTER TABLE "assemble_product_parts" ADD CONSTRAINT "assemble_product_parts_ibfk_1" FOREIGN KEY ("part_product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "assemble_product_parts" ("part_product_id");
ALTER TABLE "assemble_products" ADD CONSTRAINT "assemble_products_ibfk_1" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "assemble_products" ("product_id");
ALTER TABLE "assemble_products" ADD CONSTRAINT "assemble_products_ibfk_2" FOREIGN KEY ("inventory_id") REFERENCES "inventories" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "assemble_products" ("inventory_id");
ALTER TABLE "attachments" ADD CONSTRAINT "attachments_ibfk_1" FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "attachments" ("created_by");
ALTER TABLE "bank_transactions" ADD CONSTRAINT "bank_transactions_ibfk_1" FOREIGN KEY ("ledger_id") REFERENCES "ledgers" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "bank_transactions" ("ledger_id");
ALTER TABLE "banks" ADD CONSTRAINT "banks_ibfk_1" FOREIGN KEY ("id") REFERENCES "parties" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "banks" ("id");
ALTER TABLE "bookings" ADD CONSTRAINT "booking_ibfk_1" FOREIGN KEY ("id") REFERENCES "commercial_docs" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "bookings" ("id");
ALTER TABLE "branches" ADD CONSTRAINT "branches_ibfk_1" FOREIGN KEY ("address_id") REFERENCES "addresses" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "branches" ("address_id");
ALTER TABLE "budgets" ADD CONSTRAINT "budgets_ibfk_1" FOREIGN KEY ("budget_id") REFERENCES "account_budgets" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "budgets" ("budget_id");
ALTER TABLE "cheques" ADD CONSTRAINT "cheques_ibfk_1" FOREIGN KEY ("party_id") REFERENCES "parties" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "cheques" ("party_id");
ALTER TABLE "cheques" ADD CONSTRAINT "cheques_ibfk_2" FOREIGN KEY ("bank_id") REFERENCES "banks" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "cheques" ("bank_id");
ALTER TABLE "cheques" ADD CONSTRAINT "cheques_ibfk_3" FOREIGN KEY ("journal_id") REFERENCES "journals" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "cheques" ("journal_id");
ALTER TABLE "cheques" ADD CONSTRAINT "cheques_ibfk_4" FOREIGN KEY ("account_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "cheques" ("account_id");
ALTER TABLE "cheques" ADD CONSTRAINT "cheques_ibfk_5" FOREIGN KEY ("voucher_id") REFERENCES "vouchers" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "cheques" ("voucher_id");
ALTER TABLE "claim_problems" ADD CONSTRAINT "claim_problems_ibfk_1" FOREIGN KEY ("warranty_claim_id") REFERENCES "warranty_claims" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "claim_problems" ("warranty_claim_id");
ALTER TABLE "claim_problems" ADD CONSTRAINT "claim_problems_ibfk_2" FOREIGN KEY ("problem_id") REFERENCES "claim_related_problems" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "claim_problems" ("problem_id");
ALTER TABLE "cnf_agents" ADD CONSTRAINT "cnf_agents_ibfk_1" FOREIGN KEY ("id") REFERENCES "parties" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "cnf_agents" ("id");
ALTER TABLE "commercial_doc_items" ADD CONSTRAINT "commercial_doc_ibfk_1" FOREIGN KEY ("commercial_doc_id") REFERENCES "commercial_docs" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "commercial_doc_items" ("commercial_doc_id");
ALTER TABLE "commercial_doc_items" ADD CONSTRAINT "product_ibfk_2" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "commercial_doc_items" ("product_id");
ALTER TABLE "commercial_docs" ADD CONSTRAINT "commercial_docs_ibfk_1" FOREIGN KEY ("production_program_id") REFERENCES "production_programs" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "commercial_docs" ("production_program_id");
ALTER TABLE "companies" ADD CONSTRAINT "companies_ibfk_1" FOREIGN KEY ("address_id") REFERENCES "addresses" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "companies" ("address_id");
ALTER TABLE "customers" ADD CONSTRAINT "customers_ibfk_1" FOREIGN KEY ("id") REFERENCES "parties" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "customers" ("id");
ALTER TABLE "deliveries" ADD CONSTRAINT "deliveries_ibfk_1" FOREIGN KEY ("id") REFERENCES "vouchers" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "deliveries" ("id");
ALTER TABLE "deliveries" ADD CONSTRAINT "deliveries_ibfk_2" FOREIGN KEY ("order_id") REFERENCES "vouchers" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "deliveries" ("order_id");
ALTER TABLE "delivery_products" ADD CONSTRAINT "delivery_products_ibfk_1" FOREIGN KEY ("delivery_id") REFERENCES "deliveries" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "delivery_products" ("delivery_id");
ALTER TABLE "delivery_products" ADD CONSTRAINT "delivery_products_ibfk_2" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "delivery_products" ("product_id");
ALTER TABLE "delivery_products" ADD CONSTRAINT "delivery_products_ibfk_3" FOREIGN KEY ("order_id") REFERENCES "vouchers" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "delivery_products" ("order_id");
ALTER TABLE "delivery_status" ADD CONSTRAINT "delivery_status_ibfk_1" FOREIGN KEY ("delivery_id") REFERENCES "deliveries" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "delivery_status" ("delivery_id");
ALTER TABLE "departments" ADD CONSTRAINT "departments_ibfk_1" FOREIGN KEY ("parent_id") REFERENCES "departments" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "departments" ("parent_id");
ALTER TABLE "draft_ledgers" ADD CONSTRAINT "draft_ledgers_ibfk_2" FOREIGN KEY ("account_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "draft_ledgers" ("account_id");
ALTER TABLE "draft_ledgers" ADD CONSTRAINT "draft_ledgers_ibfk_3" FOREIGN KEY ("party_id") REFERENCES "parties" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "draft_ledgers" ("party_id");
ALTER TABLE "draft_ledgers" ADD CONSTRAINT "draft_ledgers_ibfk_4" FOREIGN KEY ("voucher_id") REFERENCES "vouchers" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "draft_ledgers" ("voucher_id");
ALTER TABLE "employee_payscales" ADD CONSTRAINT "employee_payscales_ibfk_1" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "employee_payscales" ("employee_id");
ALTER TABLE "employee_sale_targets" ADD CONSTRAINT "employee_sale_targets_ibfk_1" FOREIGN KEY ("target_id") REFERENCES "sale_targets" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "employee_sale_targets" ("target_id");
ALTER TABLE "employee_sale_targets" ADD CONSTRAINT "employee_sale_targets_ibfk_2" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "employee_sale_targets" ("employee_id");
ALTER TABLE "employee_schedules" ADD CONSTRAINT "employee_schedules_ibfk_1" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "employee_schedules" ("employee_id");
ALTER TABLE "employments" ADD CONSTRAINT "employments_ibfk_1" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "employments" ("employee_id");
ALTER TABLE "enquiry_status_histories" ADD CONSTRAINT "enquiry_status_histories_ibfk_1" FOREIGN KEY ("enquiry_id") REFERENCES "sample_enquiries" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "enquiry_status_histories" ("enquiry_id");
ALTER TABLE "export_lc_couriers" ADD CONSTRAINT "export_lc_courier_ibfk_1" FOREIGN KEY ("id") REFERENCES "commercial_docs" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "export_lc_couriers" ("id");
ALTER TABLE "export_lc_couriers" ADD CONSTRAINT "export_lc_courier_ibfk_2" FOREIGN KEY ("lc_id") REFERENCES "export_lcs" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "export_lc_couriers" ("lc_id");
ALTER TABLE "export_lc_documents" ADD CONSTRAINT "export_lc_document_ibfk_1" FOREIGN KEY ("id") REFERENCES "commercial_docs" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "export_lc_documents" ("id");
ALTER TABLE "export_lcs" ADD CONSTRAINT "export_lcs_ibfk_1" FOREIGN KEY ("id") REFERENCES "sale_orders" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "export_lcs" ("id");
ALTER TABLE "factories" ADD CONSTRAINT "factories_ibfk_1" FOREIGN KEY ("id") REFERENCES "parties" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "factories" ("id");
ALTER TABLE "features" ADD CONSTRAINT "features_ibfk_1" FOREIGN KEY ("unit_of_measurement_id") REFERENCES "units_of_measurement" ("id") ON DELETE SET NULL ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "features" ("unit_of_measurement_id");
ALTER TABLE "finished_product_receive" ADD CONSTRAINT "finished_product_receive_ibfk_1" FOREIGN KEY ("production_id") REFERENCES "productions" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "finished_product_receive" ("production_id");
ALTER TABLE "finished_product_receive" ADD CONSTRAINT "finished_product_receive_ibfk_2" FOREIGN KEY ("production_step_id") REFERENCES "production_steps" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "finished_product_receive" ("production_step_id");
ALTER TABLE "finished_product_receive" ADD CONSTRAINT "finished_product_receive_ibfk_3" FOREIGN KEY ("workorder_id") REFERENCES "receive_workorders" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "finished_product_receive" ("workorder_id");
ALTER TABLE "finished_product_receive" ADD CONSTRAINT "finished_product_receive_ibfk_4" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "finished_product_receive" ("product_id");
ALTER TABLE "finished_product_receive" ADD CONSTRAINT "finished_product_receive_ibfk_5" FOREIGN KEY ("finished_product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "finished_product_receive" ("finished_product_id");
ALTER TABLE "holiday_types" ADD CONSTRAINT "holiday_types_ibfk_1" FOREIGN KEY ("holiday_policy_id") REFERENCES "holiday_policies" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "holiday_types" ("holiday_policy_id");
ALTER TABLE "holidays" ADD CONSTRAINT "holidays_ibfk_1" FOREIGN KEY ("holiday_type_id") REFERENCES "holiday_types" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "holidays" ("holiday_type_id");
ALTER TABLE "holidays" ADD CONSTRAINT "holidays_ibfk_2" FOREIGN KEY ("holiday_policy_id") REFERENCES "holiday_policies" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "holidays" ("holiday_policy_id");
ALTER TABLE "import_lc_couriers" ADD CONSTRAINT "import_lc_courier_ibfk_1" FOREIGN KEY ("id") REFERENCES "commercial_docs" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "import_lc_couriers" ("id");
ALTER TABLE "import_lc_couriers" ADD CONSTRAINT "import_lc_courier_ibfk_2" FOREIGN KEY ("lc_id") REFERENCES "import_lcs" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "import_lc_couriers" ("lc_id");
ALTER TABLE "import_lc_documents" ADD CONSTRAINT "import_lc_document_ibfk_1" FOREIGN KEY ("id") REFERENCES "commercial_docs" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "import_lc_documents" ("id");
ALTER TABLE "import_lcs" ADD CONSTRAINT "import_lcs_ibfk_1" FOREIGN KEY ("id") REFERENCES "purchase_orders" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "import_lcs" ("id");
ALTER TABLE "import_lcs" ADD CONSTRAINT "import_lcs_ibfk_3" FOREIGN KEY ("cnf_agent_id") REFERENCES "cnf_agents" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "import_lcs" ("cnf_agent_id");
ALTER TABLE "import_lcs" ADD CONSTRAINT "import_lcs_ibfk_4" FOREIGN KEY ("master_lc_id") REFERENCES "export_lcs" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "import_lcs" ("master_lc_id");
ALTER TABLE "inventories" ADD CONSTRAINT "inventories_ibfk_1" FOREIGN KEY ("account_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "inventories" ("account_id");
ALTER TABLE "inventory_journals" ADD CONSTRAINT "inventory_journals_ibfk_1" FOREIGN KEY ("delivery_id") REFERENCES "deliveries" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "inventory_journals" ("delivery_id");
ALTER TABLE "inventory_products" ADD CONSTRAINT "inventory_products_ibfk_1" FOREIGN KEY ("inventory_id") REFERENCES "inventories" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "inventory_products" ("inventory_id");
ALTER TABLE "item_features" ADD CONSTRAINT "item_features_ibfk_1" FOREIGN KEY ("item_id") REFERENCES "items" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "item_features" ("item_id");
ALTER TABLE "item_features" ADD CONSTRAINT "item_features_ibfk_2" FOREIGN KEY ("feature_id") REFERENCES "features" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "item_features" ("feature_id");
ALTER TABLE "items" ADD CONSTRAINT "items_ibfk_1" FOREIGN KEY ("unit_of_measurement_id") REFERENCES "units_of_measurement" ("id") ON DELETE SET NULL ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "items" ("unit_of_measurement_id");
ALTER TABLE "journals" ADD CONSTRAINT "journals_ibfk_1" FOREIGN KEY ("party_id") REFERENCES "parties" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "journals" ("party_id");
ALTER TABLE "journals" ADD CONSTRAINT "journals_ibfk_2" FOREIGN KEY ("voucher_id") REFERENCES "vouchers" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "journals" ("voucher_id");
ALTER TABLE "journals" ADD CONSTRAINT "journals_ibfk_3" FOREIGN KEY ("branch_id") REFERENCES "branches" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "journals" ("branch_id");
ALTER TABLE "lc_purchase_orders" ADD CONSTRAINT "lc_purchase_orders_ibfk_1" FOREIGN KEY ("lc_id") REFERENCES "export_lcs" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "lc_purchase_orders" ("lc_id");
ALTER TABLE "lc_purchase_orders" ADD CONSTRAINT "lc_purchase_orders_ibfk_2" FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "lc_purchase_orders" ("purchase_order_id");
ALTER TABLE "lcs" ADD CONSTRAINT "lcs_ibfk_1" FOREIGN KEY ("id") REFERENCES "commercial_docs" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "lcs" ("id");
ALTER TABLE "loan_repayments" ADD CONSTRAINT "loan_repayments_ibfk_1" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "loan_repayments" ("employee_id");
ALTER TABLE "loan_repayments" ADD CONSTRAINT "loan_repayments_ibfk_2" FOREIGN KEY ("loan_id") REFERENCES "loans" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "loan_repayments" ("loan_id");
ALTER TABLE "loan_repayments" ADD CONSTRAINT "loan_repayments_ibfk_3" FOREIGN KEY ("payroll_schedule_id") REFERENCES "all_payroll_schedules" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "loan_repayments" ("payroll_schedule_id");
ALTER TABLE "loans" ADD CONSTRAINT "loans_ibfk_1" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "loans" ("employee_id");
ALTER TABLE "manufacturers" ADD CONSTRAINT "manufacturers_ibfk_1" FOREIGN KEY ("id") REFERENCES "parties" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "manufacturers" ("id");
ALTER TABLE "modules" ADD CONSTRAINT "modules_ibfk_1" FOREIGN KEY ("app_id") REFERENCES "applications" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "modules" ("app_id");
ALTER TABLE "order_amendments" ADD CONSTRAINT "order_amendments_ibfk_1" FOREIGN KEY ("order_id") REFERENCES "vouchers" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "order_amendments" ("order_id");
ALTER TABLE "order_invoice_products" ADD CONSTRAINT "order_invoice_product_ibfk_1" FOREIGN KEY ("invoice_id") REFERENCES "order_invoices" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "order_invoice_products" ("invoice_id");
ALTER TABLE "order_invoice_products" ADD CONSTRAINT "order_invoice_product_ibfk_2" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "order_invoice_products" ("product_id");
ALTER TABLE "order_invoices" ADD CONSTRAINT "order_invoice_ibfk_1" FOREIGN KEY ("order_id") REFERENCES "vouchers" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "order_invoices" ("order_id");
ALTER TABLE "order_item_diffs" ADD CONSTRAINT "order_item_diffs_ibfk_1" FOREIGN KEY ("amendment_id") REFERENCES "order_amendments" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "order_item_diffs" ("amendment_id");
ALTER TABLE "order_item_diffs" ADD CONSTRAINT "order_item_diffs_ibfk_2" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "order_item_diffs" ("product_id");
ALTER TABLE "order_item_diffs" ADD CONSTRAINT "order_item_diffs_ibfk_3" FOREIGN KEY ("order_item_id") REFERENCES "order_items" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "order_item_diffs" ("order_item_id");
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_table_ibfk_1" FOREIGN KEY ("order_id") REFERENCES "vouchers" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "order_items" ("order_id");
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_table_ibfk_2" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "order_items" ("product_id");
ALTER TABLE "order_vouchers" ADD CONSTRAINT "order_vouchers_ibfk_1" FOREIGN KEY ("voucher_id") REFERENCES "vouchers" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "order_vouchers" ("voucher_id");
ALTER TABLE "order_vouchers" ADD CONSTRAINT "order_vouchers_ibfk_2" FOREIGN KEY ("order_id") REFERENCES "vouchers" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "order_vouchers" ("order_id");
ALTER TABLE "parties" ADD CONSTRAINT "parties_ibfk_1" FOREIGN KEY ("branch_id") REFERENCES "branches" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "parties" ("branch_id");
ALTER TABLE "parties" ADD CONSTRAINT "parties_ibfk_2" FOREIGN KEY ("late_fee_policy_id") REFERENCES "late_fee_policies" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "parties" ("late_fee_policy_id");
ALTER TABLE "party_ledgers" ADD CONSTRAINT "party_ledgers_ibfk_1" FOREIGN KEY ("journal_id") REFERENCES "journals" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "party_ledgers" ("journal_id");
ALTER TABLE "party_ledgers" ADD CONSTRAINT "party_ledgers_ibfk_2" FOREIGN KEY ("voucher_id") REFERENCES "vouchers" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "party_ledgers" ("voucher_id");
ALTER TABLE "party_ledgers" ADD CONSTRAINT "party_ledgers_ibfk_3" FOREIGN KEY ("party_id") REFERENCES "parties" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "party_ledgers" ("party_id");
ALTER TABLE "party_ledgers" ADD CONSTRAINT "party_ledgers_ibfk_4" FOREIGN KEY ("branch_id") REFERENCES "branches" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "party_ledgers" ("branch_id");
ALTER TABLE "party_supervisors" ADD CONSTRAINT "party_supervisors_ibfk_1" FOREIGN KEY ("party_id") REFERENCES "parties" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "party_supervisors" ("party_id");
ALTER TABLE "party_supervisors" ADD CONSTRAINT "party_supervisors_ibfk_2" FOREIGN KEY ("other_party_id") REFERENCES "parties" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "party_supervisors" ("other_party_id");
ALTER TABLE "party_users" ADD CONSTRAINT "party_users_ibfk_1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "party_users" ("user_id");
ALTER TABLE "party_users" ADD CONSTRAINT "party_users_ibfk_2" FOREIGN KEY ("party_id") REFERENCES "parties" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "party_users" ("party_id");
ALTER TABLE "payroll_vendors" ADD CONSTRAINT "payroll_vendors_ibfk_1" FOREIGN KEY ("id") REFERENCES "parties" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "payroll_vendors" ("id");
ALTER TABLE "piecework_rates" ADD CONSTRAINT "piecework_rates_ibfk_1" FOREIGN KEY ("step_id") REFERENCES "production_program_steps" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "piecework_rates" ("step_id");
ALTER TABLE "pre_costing" ADD CONSTRAINT "pre_costing_ibfk_1" FOREIGN KEY ("production_program_id") REFERENCES "production_programs" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "pre_costing" ("production_program_id");
ALTER TABLE "process_inventory_lines" ADD CONSTRAINT "process_inventory_lines_ibfk_1" FOREIGN KEY ("floor_id") REFERENCES "process_inventory_floors" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "process_inventory_lines" ("floor_id");
ALTER TABLE "product_features" ADD CONSTRAINT "product_features_ibfk_1" FOREIGN KEY ("feature_id") REFERENCES "features" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "product_features" ("feature_id");
ALTER TABLE "product_group_feature_options" ADD CONSTRAINT "product_group_feature_options_ibfk_1" FOREIGN KEY ("product_group_id") REFERENCES "product_groups" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "product_group_feature_options" ("product_group_id");
ALTER TABLE "product_group_feature_options" ADD CONSTRAINT "product_group_feature_options_ibfk_2" FOREIGN KEY ("feature_id") REFERENCES "features" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "product_group_feature_options" ("feature_id");
ALTER TABLE "product_group_features" ADD CONSTRAINT "product_group_features_ibfk_1" FOREIGN KEY ("product_group_id") REFERENCES "product_groups" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "product_group_features" ("product_group_id");
ALTER TABLE "product_group_features" ADD CONSTRAINT "product_group_features_ibfk_2" FOREIGN KEY ("feature_id") REFERENCES "features" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "product_group_features" ("feature_id");
ALTER TABLE "product_groups" ADD CONSTRAINT "product_groups_ibfk_1" FOREIGN KEY ("item_id") REFERENCES "items" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "product_groups" ("item_id");
ALTER TABLE "product_prices" ADD CONSTRAINT "product_prices_ibfk_1" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "product_prices" ("product_id");
ALTER TABLE "product_service_vouchers" ADD CONSTRAINT "product_service_vouchers_ibfk_1" FOREIGN KEY ("warranty_claim_id") REFERENCES "warranty_claims" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "product_service_vouchers" ("warranty_claim_id");
ALTER TABLE "product_service_vouchers" ADD CONSTRAINT "product_service_vouchers_ibfk_2" FOREIGN KEY ("voucher_id") REFERENCES "vouchers" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "product_service_vouchers" ("voucher_id");
ALTER TABLE "production_planning" ADD CONSTRAINT "production_planning_ibfk_1" FOREIGN KEY ("production_id") REFERENCES "productions" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "production_planning" ("production_id");
ALTER TABLE "production_planning" ADD CONSTRAINT "production_planning_ibfk_2" FOREIGN KEY ("production_step_id") REFERENCES "production_steps" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "production_planning" ("production_step_id");
ALTER TABLE "production_planning" ADD CONSTRAINT "production_planning_ibfk_3" FOREIGN KEY ("machine_id") REFERENCES "machines" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "production_planning" ("machine_id");
ALTER TABLE "production_planning" ADD CONSTRAINT "production_planning_ibfk_4" FOREIGN KEY ("workorder_id") REFERENCES "receive_workorders" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "production_planning" ("workorder_id");
ALTER TABLE "production_program_steps" ADD CONSTRAINT "production_program_steps_ibfk_1" FOREIGN KEY ("production_program_outline_id") REFERENCES "production_program_outlines" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "production_program_steps" ("production_program_outline_id");
ALTER TABLE "production_program_substeps" ADD CONSTRAINT "production_program_substeps_ibfk_1" FOREIGN KEY ("step_id") REFERENCES "production_program_steps" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "production_program_substeps" ("step_id");
ALTER TABLE "production_program_values" ADD CONSTRAINT "production_program_values_ibfk_1" FOREIGN KEY ("production_program_id") REFERENCES "production_programs" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "production_program_values" ("production_program_id");
ALTER TABLE "production_program_values" ADD CONSTRAINT "production_program_values_ibfk_2" FOREIGN KEY ("step_id") REFERENCES "production_program_steps" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "production_program_values" ("step_id");
ALTER TABLE "production_program_values" ADD CONSTRAINT "production_program_values_ibfk_3" FOREIGN KEY ("substep_id") REFERENCES "production_program_substeps" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "production_program_values" ("substep_id");
ALTER TABLE "production_programs" ADD CONSTRAINT "production_programs_ibfk_1" FOREIGN KEY ("party_id") REFERENCES "parties" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "production_programs" ("party_id");
ALTER TABLE "production_programs" ADD CONSTRAINT "production_programs_ibfk_2" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "production_programs" ("employee_id");
ALTER TABLE "production_step_products" ADD CONSTRAINT "production_step_products_ibfk_1" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "production_step_products" ("product_id");
ALTER TABLE "production_step_products" ADD CONSTRAINT "production_step_products_ibfk_2" FOREIGN KEY ("step_id") REFERENCES "production_steps" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "production_step_products" ("step_id");
ALTER TABLE "production_steps" ADD CONSTRAINT "production_steps_ibfk_1" FOREIGN KEY ("production_outline_id") REFERENCES "production_outlines" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "production_steps" ("production_outline_id");
ALTER TABLE "productions" ADD CONSTRAINT "productions_ibfk_1" FOREIGN KEY ("id") REFERENCES "vouchers" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "productions" ("id");
ALTER TABLE "productions" ADD CONSTRAINT "productions_ibfk_2" FOREIGN KEY ("production_program_id") REFERENCES "production_programs" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "productions" ("production_program_id");
ALTER TABLE "products" ADD CONSTRAINT "products_ibfk_1" FOREIGN KEY ("item_id") REFERENCES "items" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "products" ("item_id");
ALTER TABLE "products" ADD CONSTRAINT "products_ibfk_2" FOREIGN KEY ("vendor_id") REFERENCES "vendors" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "products" ("vendor_id");
ALTER TABLE "products" ADD CONSTRAINT "products_ibfk_3" FOREIGN KEY ("manufacturer_id") REFERENCES "manufacturers" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "products" ("manufacturer_id");
ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_ibfk_1" FOREIGN KEY ("id") REFERENCES "vouchers" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "purchase_orders" ("id");
ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_ibfk_2" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "purchase_orders" ("employee_id");
ALTER TABLE "raw_material_issue" ADD CONSTRAINT "raw_material_issue_ibfk_1" FOREIGN KEY ("production_id") REFERENCES "productions" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "raw_material_issue" ("production_id");
ALTER TABLE "raw_material_issue" ADD CONSTRAINT "raw_material_issue_ibfk_2" FOREIGN KEY ("production_step_id") REFERENCES "production_steps" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "raw_material_issue" ("production_step_id");
ALTER TABLE "raw_material_issue" ADD CONSTRAINT "raw_material_issue_ibfk_3" FOREIGN KEY ("workorder_id") REFERENCES "receive_workorders" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "raw_material_issue" ("workorder_id");
ALTER TABLE "raw_material_issue" ADD CONSTRAINT "raw_material_issue_ibfk_4" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "raw_material_issue" ("product_id");
ALTER TABLE "raw_material_issue" ADD CONSTRAINT "raw_material_issue_ibfk_5" FOREIGN KEY ("finished_product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "raw_material_issue" ("finished_product_id");
ALTER TABLE "raw_order_items" ADD CONSTRAINT "raw_order_items_ibfk_1" FOREIGN KEY ("order_id") REFERENCES "vouchers" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "raw_order_items" ("order_id");
ALTER TABLE "raw_order_items" ADD CONSTRAINT "raw_order_items_ibfk_2" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "raw_order_items" ("product_id");
ALTER TABLE "raw_order_items" ADD CONSTRAINT "raw_order_items_ibfk_3" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "raw_order_items" ("project_id");
ALTER TABLE "receive_proforma_invoices" ADD CONSTRAINT "receive_proforma_invoice_ibfk_1" FOREIGN KEY ("id") REFERENCES "commercial_docs" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "receive_proforma_invoices" ("id");
ALTER TABLE "receive_purchase_requests" ADD CONSTRAINT "receive_purchase_request_ibfk_1" FOREIGN KEY ("id") REFERENCES "commercial_docs" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "receive_purchase_requests" ("id");
ALTER TABLE "receive_quotations" ADD CONSTRAINT "receive_quotation_ibfk_1" FOREIGN KEY ("id") REFERENCES "commercial_docs" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "receive_quotations" ("id");
ALTER TABLE "receive_sample_orders" ADD CONSTRAINT "receive_sample_order_ibfk_1" FOREIGN KEY ("id") REFERENCES "commercial_docs" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "receive_sample_orders" ("id");
ALTER TABLE "receive_sample_orders" ADD CONSTRAINT "receive_sample_order_ibfk_2" FOREIGN KEY ("factory_id") REFERENCES "factories" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "receive_sample_orders" ("factory_id");
ALTER TABLE "receive_workorders" ADD CONSTRAINT "receive_workorder_ibfk_1" FOREIGN KEY ("id") REFERENCES "commercial_docs" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "receive_workorders" ("id");
ALTER TABLE "requisition_products" ADD CONSTRAINT "requisition_products_ibfk_1" FOREIGN KEY ("requisition_id") REFERENCES "requisitions" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "requisition_products" ("requisition_id");
ALTER TABLE "requisition_products" ADD CONSTRAINT "requisition_products_ibfk_2" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "requisition_products" ("product_id");
ALTER TABLE "requisitions" ADD CONSTRAINT "requisitions_ibfk_1" FOREIGN KEY ("department_id") REFERENCES "departments" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "requisitions" ("department_id");
ALTER TABLE "sale_contacts" ADD CONSTRAINT "sale_contact_ibfk_1" FOREIGN KEY ("id") REFERENCES "commercial_docs" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "sale_contacts" ("id");
ALTER TABLE "sale_orders" ADD CONSTRAINT "sale_orders_ibfk_1" FOREIGN KEY ("id") REFERENCES "vouchers" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "sale_orders" ("id");
ALTER TABLE "send_proforma_invoices" ADD CONSTRAINT "send_proforma_invoice_ibfk_1" FOREIGN KEY ("id") REFERENCES "commercial_docs" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "send_proforma_invoices" ("id");
ALTER TABLE "send_purchase_requests" ADD CONSTRAINT "send_purchase_request_ibfk_1" FOREIGN KEY ("id") REFERENCES "commercial_docs" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "send_purchase_requests" ("id");
ALTER TABLE "send_quotations" ADD CONSTRAINT "send_quotation_ibfk_1" FOREIGN KEY ("id") REFERENCES "commercial_docs" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "send_quotations" ("id");
ALTER TABLE "send_sample_orders" ADD CONSTRAINT "send_sample_order_ibfk_1" FOREIGN KEY ("id") REFERENCES "commercial_docs" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "send_sample_orders" ("id");
ALTER TABLE "send_sample_orders" ADD CONSTRAINT "send_sample_order_ibfk_2" FOREIGN KEY ("factory_id") REFERENCES "factories" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "send_sample_orders" ("factory_id");
ALTER TABLE "send_techspecs" ADD CONSTRAINT "techspec_ibfk_1" FOREIGN KEY ("id") REFERENCES "commercial_docs" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "send_techspecs" ("id");
ALTER TABLE "send_workorders" ADD CONSTRAINT "send_workorder_ibfk_1" FOREIGN KEY ("id") REFERENCES "commercial_docs" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "send_workorders" ("id");
ALTER TABLE "service_contract_products" ADD CONSTRAINT "service_contract_products_ibfk_1" FOREIGN KEY ("service_contract_id") REFERENCES "service_contracts" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "service_contract_products" ("service_contract_id");
ALTER TABLE "service_contract_products" ADD CONSTRAINT "service_contract_products_ibfk_2" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "service_contract_products" ("product_id");
ALTER TABLE "service_contract_products" ADD CONSTRAINT "service_contract_products_ibfk_3" FOREIGN KEY ("billingcycle_id") REFERENCES "billingcycles" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "service_contract_products" ("billingcycle_id");
ALTER TABLE "service_contracts" ADD CONSTRAINT "service_contracts_ibfk_1" FOREIGN KEY ("party_id") REFERENCES "parties" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "service_contracts" ("party_id");
ALTER TABLE "service_contracts" ADD CONSTRAINT "service_contracts_ibfk_2" FOREIGN KEY ("service_package_id") REFERENCES "service_packages" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "service_contracts" ("service_package_id");
ALTER TABLE "service_package_products" ADD CONSTRAINT "service_package_products_ibfk_1" FOREIGN KEY ("service_package_id") REFERENCES "service_packages" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "service_package_products" ("service_package_id");
ALTER TABLE "service_package_products" ADD CONSTRAINT "service_package_products_ibfk_2" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "service_package_products" ("product_id");
ALTER TABLE "service_products" ADD CONSTRAINT "service_products_ibfk_1" FOREIGN KEY ("warranty_claim_id") REFERENCES "warranty_claims" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "service_products" ("warranty_claim_id");
ALTER TABLE "service_products" ADD CONSTRAINT "service_products_ibfk_2" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "service_products" ("product_id");
ALTER TABLE "service_vouchers" ADD CONSTRAINT "service_vouchers_ibfk_1" FOREIGN KEY ("party_id") REFERENCES "parties" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "service_vouchers" ("party_id");
ALTER TABLE "service_vouchers" ADD CONSTRAINT "service_vouchers_ibfk_2" FOREIGN KEY ("voucher_id") REFERENCES "vouchers" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "service_vouchers" ("voucher_id");
ALTER TABLE "service_vouchers" ADD CONSTRAINT "service_vouchers_ibfk_3" FOREIGN KEY ("parent_id") REFERENCES "service_vouchers" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "service_vouchers" ("parent_id");
ALTER TABLE "shift_slots" ADD CONSTRAINT "shift_slots_ibfk_1" FOREIGN KEY ("shift_schedule_id") REFERENCES "shift_schedules" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "shift_slots" ("shift_schedule_id");
ALTER TABLE "specialization" ADD CONSTRAINT "specialization_ibfk_1" FOREIGN KEY ("department_id") REFERENCES "departments" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "specialization" ("department_id");
ALTER TABLE "unit_multipliers" ADD CONSTRAINT "unit_multipliers_ibfk_1" FOREIGN KEY ("unit_of_mesaurement_id") REFERENCES "units_of_measurement" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "unit_multipliers" ("unit_of_mesaurement_id");
ALTER TABLE "unit_multipliers" ADD CONSTRAINT "unit_multipliers_ibfk_2" FOREIGN KEY ("multiplier_id") REFERENCES "multipliers" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "unit_multipliers" ("multiplier_id");
ALTER TABLE "users" ADD CONSTRAINT "users_ibfk_1" FOREIGN KEY ("profile_id") REFERENCES "parties" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "users" ("profile_id");
ALTER TABLE "vendors" ADD CONSTRAINT "vendors_ibfk_1" FOREIGN KEY ("id") REFERENCES "parties" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "vendors" ("id");
ALTER TABLE "voucher_products" ADD CONSTRAINT "voucher_products_ibfk_1" FOREIGN KEY ("voucher_id") REFERENCES "vouchers" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "voucher_products" ("voucher_id");
ALTER TABLE "voucher_products" ADD CONSTRAINT "voucher_products_ibfk_2" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "voucher_products" ("product_id");
ALTER TABLE "voucher_products" ADD CONSTRAINT "voucher_products_ibfk_3" FOREIGN KEY ("service_contract_id") REFERENCES "service_contracts" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "voucher_products" ("service_contract_id");
ALTER TABLE "voucher_products" ADD CONSTRAINT "voucher_products_ibfk_4" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "voucher_products" ("project_id");
ALTER TABLE "vouchers" ADD CONSTRAINT "vouchers_ibfk_2" FOREIGN KEY ("party_id") REFERENCES "parties" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "vouchers" ("party_id");
ALTER TABLE "vouchers" ADD CONSTRAINT "vouchers_ibfk_3" FOREIGN KEY ("account_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "vouchers" ("account_id");
ALTER TABLE "vouchers" ADD CONSTRAINT "vouchers_ibfk_4" FOREIGN KEY ("contra_account_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "vouchers" ("contra_account_id");
ALTER TABLE "vouchers" ADD CONSTRAINT "vouchers_ibfk_6" FOREIGN KEY ("subtype") REFERENCES "custom_vouchers" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "vouchers" ("subtype");
ALTER TABLE "vouchers" ADD CONSTRAINT "vouchers_ibfk_7" FOREIGN KEY ("branch_id") REFERENCES "branches" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "vouchers" ("branch_id");
ALTER TABLE "warranty_claims" ADD CONSTRAINT "warranty_claims_ibfk_2" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "warranty_claims" ("product_id");
ALTER TABLE "warranty_claims" ADD CONSTRAINT "warranty_claims_ibfk_4" FOREIGN KEY ("branch_id") REFERENCES "branches" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "warranty_claims" ("branch_id");
ALTER TABLE "warranty_claims_status" ADD CONSTRAINT "warranty_claims_status_ibfk_1" FOREIGN KEY ("warranty_claim_id") REFERENCES "warranty_claims" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "warranty_claims_status" ("warranty_claim_id");
ALTER TABLE "warranty_products" ADD CONSTRAINT "warranty_products_ibfk_1" FOREIGN KEY ("warranty_claim_id") REFERENCES "warranty_claims" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "warranty_products" ("warranty_claim_id");
ALTER TABLE "warranty_products" ADD CONSTRAINT "warranty_products_ibfk_2" FOREIGN KEY ("order_item_id") REFERENCES "order_items" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "warranty_products" ("order_item_id");
ALTER TABLE "warranty_products" ADD CONSTRAINT "warranty_products_ibfk_3" FOREIGN KEY ("solution_id") REFERENCES "warranty_solutions" ("id") ON DELETE SET NULL ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "warranty_products" ("solution_id");
ALTER TABLE "warranty_solutions" ADD CONSTRAINT "warranty_solutions_ibfk_1" FOREIGN KEY ("warranty_claim_id") REFERENCES "warranty_claims" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "warranty_solutions" ("warranty_claim_id");
ALTER TABLE "warranty_solutions" ADD CONSTRAINT "warranty_solutions_ibfk_2" FOREIGN KEY ("warranty_product_id") REFERENCES "warranty_products" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "warranty_solutions" ("warranty_product_id");
ALTER TABLE "warranty_solutions" ADD CONSTRAINT "warranty_solutions_ibfk_3" FOREIGN KEY ("solution_voucher_id") REFERENCES "vouchers" ("id") ON DELETE SET NULL ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "warranty_solutions" ("solution_voucher_id");
ALTER TABLE "warranty_solutions" ADD CONSTRAINT "warranty_solutions_ibfk_4" FOREIGN KEY ("replacement_inventory_id") REFERENCES "inventories" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ON "warranty_solutions" ("replacement_inventory_id");

